// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	models "test1/models"
)

// GetAccounts2OKCode is the HTTP code returned for type GetAccounts2OK
const GetAccounts2OKCode int = 200

/*GetAccounts2OK A list of records

swagger:response getAccounts2OK
*/
type GetAccounts2OK struct {

	/*
	  In: Body
	*/
	Payload []*models.GetAccounts2OKBodyItems `json:"body,omitempty"`
}

// NewGetAccounts2OK creates GetAccounts2OK with default headers values
func NewGetAccounts2OK() *GetAccounts2OK {

	return &GetAccounts2OK{}
}

// WithPayload adds the payload to the get accounts2 o k response
func (o *GetAccounts2OK) WithPayload(payload []*models.GetAccounts2OKBodyItems) *GetAccounts2OK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get accounts2 o k response
func (o *GetAccounts2OK) SetPayload(payload []*models.GetAccounts2OKBodyItems) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetAccounts2OK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	payload := o.Payload
	if payload == nil {
		payload = make([]*models.GetAccounts2OKBodyItems, 0, 50)
	}

	if err := producer.Produce(rw, payload); err != nil {
		panic(err) // let the recovery middleware deal with this
	}

}

// GetAccounts2BadRequestCode is the HTTP code returned for type GetAccounts2BadRequest
const GetAccounts2BadRequestCode int = 400

/*GetAccounts2BadRequest Record not found

swagger:response getAccounts2BadRequest
*/
type GetAccounts2BadRequest struct {
}

// NewGetAccounts2BadRequest creates GetAccounts2BadRequest with default headers values
func NewGetAccounts2BadRequest() *GetAccounts2BadRequest {

	return &GetAccounts2BadRequest{}
}

// WriteResponse to the client
func (o *GetAccounts2BadRequest) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(400)
}

/*GetAccounts2Default Sorry something went wrong

swagger:response getAccounts2Default
*/
type GetAccounts2Default struct {
	_statusCode int
}

// NewGetAccounts2Default creates GetAccounts2Default with default headers values
func NewGetAccounts2Default(code int) *GetAccounts2Default {
	if code <= 0 {
		code = 500
	}

	return &GetAccounts2Default{
		_statusCode: code,
	}
}

// WithStatusCode adds the status to the get accounts2 default response
func (o *GetAccounts2Default) WithStatusCode(code int) *GetAccounts2Default {
	o._statusCode = code
	return o
}

// SetStatusCode sets the status to the get accounts2 default response
func (o *GetAccounts2Default) SetStatusCode(code int) {
	o._statusCode = code
}

// WriteResponse to the client
func (o *GetAccounts2Default) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(o._statusCode)
}
