// Code generated by go-swagger; DO NOT EDIT.

/*
Package restapi Simple API
A simple API to learn how to write OpenAPI Specification


    Schemes:
      http
    Host: localhost
    BasePath: /v1
    Version: 1.0.0

    Consumes:
    - application/json

    Produces:
    - application/json

swagger:meta
*/
package restapi
